-- Initial Nukleio Catalog schema.
--
-- IDs are supplied by the importer/application rather than generated by D1.
-- Importers should use deterministic IDs so local validation and remote import
-- produce the same public identifiers.

CREATE TABLE educational_institutions (
    id TEXT PRIMARY KEY NOT NULL,
    source TEXT NOT NULL,
    source_id TEXT NOT NULL,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('college', 'high_school')),
    city TEXT,
    state TEXT,
    country TEXT NOT NULL DEFAULT 'US',
    website TEXT,
    logo_key TEXT,
    source_year INTEGER,
    is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    imported_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source, source_id)
);

CREATE INDEX idx_educational_institutions_normalized_name
    ON educational_institutions (normalized_name);

CREATE INDEX idx_educational_institutions_category_normalized_name
    ON educational_institutions (category, normalized_name);

CREATE TABLE technologies (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('language', 'framework', 'technology')),
    website TEXT,
    logo_key TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (normalized_name)
);

CREATE INDEX idx_technologies_category_normalized_name
    ON technologies (category, normalized_name);

CREATE TABLE catalog_aliases (
    id TEXT PRIMARY KEY NOT NULL,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('education', 'technology')),
    entity_id TEXT NOT NULL,
    alias TEXT NOT NULL,
    normalized_alias TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (entity_type, entity_id, normalized_alias)
);

CREATE INDEX idx_catalog_aliases_lookup
    ON catalog_aliases (entity_type, normalized_alias);

CREATE INDEX idx_catalog_aliases_entity
    ON catalog_aliases (entity_type, entity_id);

CREATE TABLE import_batches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source TEXT NOT NULL,
    source_year INTEGER,
    source_url TEXT,
    file_name TEXT,
    row_count INTEGER NOT NULL DEFAULT 0 CHECK (row_count >= 0),
    imported_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status TEXT NOT NULL CHECK (status IN ('running', 'dry_run', 'completed', 'failed'))
);
